import 'package:flutter/material.dart';

const seed = Color(0xFF6750A4);

const lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Colors.white,
  onPrimary: Colors.black,
  primaryContainer: Colors.white,
  onPrimaryContainer: Color(0xFF410000),
  secondary: Color(0xFF006874),
  onSecondary: Colors.white,
  secondaryContainer: Color(0xFF90F1FF),
  onSecondaryContainer: Color(0xFF001F24),
  tertiary: Color(0xFFBD110B),
  onTertiary: Colors.white,
  tertiaryContainer: Colors.white,
  onTertiaryContainer: Colors.white,
  error: Color(0xFFB3261E),
  errorContainer: Colors.white,
  onError: Colors.white,
  onErrorContainer: Color(0xFF410E0B),
  background: Colors.white,
  onBackground: Color(0xFF201A1B),
  surface: Colors.white,
  onSurface: Color(0xFF201A1B),
  surfaceVariant: Colors.white,
  onSurfaceVariant: Color(0xFF49454F),
  outline: Colors.white,
  onInverseSurface: Colors.white,
  inverseSurface: Color(0xFF362F30),
  inversePrimary: Color(0xFFFFB4A7),
  shadow: Color(0xFF000000),
);

const darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(0xFFFFB4A7),
  onPrimary: Color(0xFF680000),
  primaryContainer: Color(0xFF930000),
  onPrimaryContainer: Color(0xFFFFDAD3),
  secondary: Color(0xFF4FD8EB),
  onSecondary: Color(0xFF00363D),
  secondaryContainer: Color(0xFF004F59),
  onSecondaryContainer: Color(0xFF90F1FF),
  tertiary: Color(0xFFFFB4A7),
  onTertiary: Color(0xFF680000),
  tertiaryContainer: Color(0xFF930000),
  onTertiaryContainer: Color(0xFFFFDAD3),
  error: Color(0xFFF2B8B5),
  errorContainer: Color(0xFF8C1D18),
  onError: Color(0xFF601410),
  onErrorContainer: Color(0xFFF9DEDC),
  background: Color(0xFF201A1B),
  onBackground: Color(0xFFECDFE0),
  surface: Color(0xFF201A1B),
  onSurface: Color(0xFFECDFE0),
  surfaceVariant: Color(0xFF49454F),
  onSurfaceVariant: Color(0xFFCAC4D0),
  outline: Color(0xFF938F99),
  onInverseSurface: Color(0xFF201A1B),
  inverseSurface: Color(0xFFECDFE0),
  inversePrimary: Color(0xFFBD110B),
  shadow: Color(0xFF000000),
);
